- default.xml
Now that the repos are public, we can use git transport and allow
checking out without a github account.
This reverts commit c2bddb3ab6e63e10755cda63f8c49cbea29c909c.
> Revert "allow building with still closed source repos"

- default.xml
meta-switch was a bit too cleaned up and missed files needed for
building v4.0.0, so required to be recreated. This also changes the
commit hashes, so update meta-switch to the new commit hash.
> default.xml: update meta-switch hash with fixed history

- conf/local.conf.sample
Set the FEEDURIPREFIX to the release path.
> conf: set release FEEDURIPREFIX

- default.xml
Github just turned off the git transport on their servers, and checking
out now fails with:
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
So switch to https to make stuff build again.
> default.xml: switch git transport to https for github

- conf/local.conf.sample
- default.xml
- extra/ofdpa-gitlab.xml
- extra/tibit.xml
- release-notes.txt
*** THIS PR MUST NOT BE REBASED ***
Set the relese FEEDURIPREFIX, add a default.xml based on the nightlies and add release-notes for this release.
Since the default.xml directly references the preceeding commit, this PR must not be rebased on merge, else the default.xml will break.
Rebasing/fixing any commits after the first one is fine.
> v4.3.0: add default.xml and release notes

- default.xml
- release-notes.txt
Update baseboxd and push back the release date.
> v4.3.0: update baseboxd to fix a multi vlan regression

- default.xml
- extra/ofdpa-gitlab.xml
* meta-ofdpa: branch with fixes only
* meta-switch: branch with version bump only
* meta-open-network-linux: linux update to 5.10.78
* meta-openembedded: build fixes for newer python versions
* meta-virtualization: use HTTPS for github
> defaults.xml: update to 4.3.1 defaults

- default.xml
- extra/ofdpa-gitlab.xml
- extra/tibit.xml
Add the appropriate release default.xml, so we can build release images.
Mostly at their final revisions, except meta-ofdpa, which needs to be
updated once the final binaries exist.
> add release default.xml

- conf/local.conf.sample
Add new supported platform to sample configuration.
> accton-as5835-54x: add platform to local.conf.sample

- conf/local.conf.sample
Add new supported platform to sample configuration.
> [backport] accton-as5835-54x: add platform to local.conf.sample

- conf/local.conf.sample
- default.xml
- extra/tibit.xml
Switch to Yocto Kirkstone (4.0), the newest LTS release.
Brings proper Linux 5.15 support, newer everything and plenty of improvements and changes.
> switch to yocto kirkstone (4.0)

- default.xml
Since we moved all required files to meta-switch, we do not need
bisdn-onie-additions anymore and can drop it from the checkout.
> default.xml: drop now unused bisdn-onie-additions

- default.xml
- extra/README.md
- extra/ofdpa-gitlab.xml
Replace the external extra manifests files with additional projects in
the default.xml, assigned to non-default groups.
To avoid the internal project being checked out by default, add it to
the special group "notdefault", which prevents it from being added to
the default "all" group.
This allows having all projects in one place. Repo requires all projects
to have unique paths, so we cannot replace the open source one, but need
to use it as an additional layer. Therefore check it out as
meta-ofdpa-closed.
This requires additional changes to the internal meta-ofdpa repo to
allow coexistence with the open one to avoid name collisions.
This way the repository can be initialized as normal via
repo init -b master -u ...
and for the internal development variant
repo init -b master -u ... -g …
> default.xml: replace extra manifests with groups

- changelog.txt
- default.xml
Add default.xml and changelog.txt for 4.8.2
default.xml based on version tested on the weekend, with the following changes:
* meta-switch: include the FRR CVE fixes
* meta-ofdpa(-closed): state of v4.8.1
* bisdn-linux: point to the FEEDURIPREFIX commit in v4.8.2
> default.xml and changelog for 4.8.2

- changelog.txt
- default.xml
Set default.xml to fixed revisions based on tonight's nightly, with the
following changes:
* bisdn-linux: point to 4.8.3 branch with release FEEDURIPREFIX
* meta-open-network-linux: point to fixes branch for 4.8.3
and add a changelog.txt generated based on these values.
> v4.8.3: add release default.xml and changelog.txt

- conf/local.conf.sample
Add the new generic machines to the local.conf.sample, and switch the default from accton-as4610 to the equivalent generic-armel-iproc.
Declare the old machine names as legacy, which we may want to remove eventually.
> conf: add new generic machines and default to generic-armel-iproc

- scripts/changelog.sh
Add our script for generating detailed changelogs.
Mostly identical to the latest internal MR, except the following:
* add licence and copyright
* slightly reword the help
* drop support for older bitbake versions
* add support for differences in yocto kirkstone
* allow setting version names
* ensure tmpdir always gets deleted
* dropped the single repo mode
* allow ignoring layers
* redirect tool output to STDERR instead of dropping it
* do not return a non zero exitcode when using an external workdir
> scripts: add script for generating changelogs

- scripts/prepare_release.sh
Add a script for creating a release branch, with automatically
* setting FEEDURIPREFIX to release
* adding a changelog.txt with all commits since the previous release
* setting default.xml to fixed revision
* setting bisdn-linux in default.xml to a revision including the above changes
* Do a sanity check that the meta-ofdpa's top commit subjects are the same (but do not abort, as this may be acceptable).
Requires xmlstarlet installed for updating the default.xml.
The basic idea for automating/scripting releases as much as possible is to simplify the release process to:
1. create a branch via this script for the a release (preparation) branch and push it directly
2. test the revision rigorously
3. If deemed stable enough, create a tag of the release
4. Do the release build
Since the …
> scripts: add a script for creating release branches

- conf/local.conf.sample
We don't build them anymore, and there are no known users, so let's not offer them anymore.
> conf: drop obsolete legacy machines

- conf/local.conf.sample
- scripts/changelog.sh
- scripts/prepare_release.sh
Add a new flag for calculating fixed CVEs between two versions, and use this for the changelog for new releases.
This works by getting open CVEs for each package included in the image,
then comparing the lists.
Creates output like this:
```
Fixed CVEs:
c-ares:
CVE-2023-31124 CVE-2023-31130 CVE-2023-31147 CVE-2023-32067
dbus:
CVE-2023-34969
docker-ce:
CVE-2023-28840 CVE-2023-28841 CVE-2023-28842
```
Be aware that the check is rather slow due to rate limiting by the CVE
database.
The CVE lists are generated based on the known CVEs at changelog generation, not time of the release, so they are not "reproducible".
As an addition, slightly extend the example config with a section explaining how to enable CVE checking for the build.
> include a list of fixed CVEs in changelogs

- default.xml
- scripts/prepare_release.sh
Update the default.xml and release script to use this branch and the stable branches in all meta-layers named the same (which are initialized based on the v5.1.0 release).
All Yocto/OE layers are kept at HEAD of their respective branches, to keep receiving upstream fixes.
> v5.1.x: update default.xml and release script for stable branches

- conf/bblayers.conf.sample
When we renamed meta-switch, we also updated its path, so we need to update the bblayers.conf.sample as well to point to the new path.
Fixes: 2884b5e4dcc1 ("default.xml: update meta-switch => meta-bisdn-linux")
> conf: rename meta-switch in bblayers.conf.sample as well

- scripts/prepare_release.sh
conf/site.conf is a new file, so we need to add it explicitly before commit it.
Fixes: cfa0f7fe99c2 ("prepare_release: use site.conf instead of local.conf")
> prepare-release: fix adding site.conf to git

- .gitignore
- bisdn-linux.yaml
- ofdpa-gitlab.yaml
- release.yaml
- scripts/convert.sh
- scripts/prepare_release.sh
Add a kas project configuration for bisdn-linux and additional snippets for building OF-DPA from source or doing development/release builds.
In contrast to repo the initial checkout must be done manually, but also kas will configure the build and add any layers automatically.
So the minimal steps for building bisdn-linux via kas are:
```
$ git clone https://github.com/bisdn/bisdn-linux.git
$ cd bisdn-linux/
$ kas build bisdn-linux.yml
```
The checkout is slightly faster:
```
$ time kas checkout bisdn-linux.yml:ofdpa-gitlab.yml
...
real	0m14,519s
user	0m35,906s
sys	0m5,031s
```
```
$ repo init -g all,ofdpa-gitlab -u https://github.com/bisdn/bisdn-linux.git
$ time repo sync
...
real	2m14,857s
user	0m50,205s
sys	0m6,116s
```
Difference to the repo configuration (from templateconf) is that …
> add kas project configuration

- README.md
When building with kas-container, the variable must be named KAS_MACHINE, not MACHINE.
> README.md: fix call for building armel-iproc image

- BUILDING_DETAILS.md
- README.md
We should not rely on any defaults, as they may change, so always be explicit about the machine to build for.
> README.md: always be explicit about MACHINE

- conf/local.conf.sample
- scripts/changelog.sh
- scripts/prepare_release.sh
To make preparing a v4.x release easier as well, backport the release script and update its basebranch to 4.x.
> v4.x: add release script

- scripts/convert.sh
Our lockfiles and kas configs use .yaml, not .yml, so we need to check for a .yaml suffix.
Fixes release config generation based on kas lock file.
Fixes: 92fa3f65205d ("scripts: add a proof of concept conversion script")
> convert.sh: check for .yaml, not .yml

- scripts/prepare_release.sh
Since we managed to do a release that had an invalid version, let's add a check for the release script to check that `DISTRO_VERSION` is set to the version for which we are preparing a release.
> prepare_release.sh: add check that DISTRO_VERSION matches the release name

- scripts/prepare_release.sh
While refactoring and renaming the variable some places were missed, and the check then didn't work. Fix this by consistently using the correct variable.
Fixes: 1e28392ab39f ("prepare_release: add a check that DISTRO_VERSION is correct")
> prepare_release: fix version check
