README.md

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

use publicly accessible https link to clone git repo

---

default.xml
extra/ofdpa-gitlab.xml
extra/tibit.xml

Set all projects to their release commit hashes. Meta-ofdpa will need to be
updated to the release packages at a later step once they exist.

set v4.1.0 release defaults

---

default.xml

default.xml: update meta-ofdpa to revision with release checksums

---

conf/local.conf.sample

conf: warn about side effects of ccache use

---

conf/local.conf.sample

We now support building for it, so we should have it in the list.

conf: add accton-as7726-32x to available MACHINEs

---

default.xml
extra/ofdpa-gitlab.xml
extra/tibit.xml

Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>

v4.2.0: add default.xml

---

extra/ofdpa-gitlab.xml

A testing revision accidentially crept in, which does not exist anymore,
so point to the appropriate revision on master.

extra/ofdpa-gitlab.xml: fix meta-ofdpa revision

---

release-notes.txt

v4.3.1: add release notes

---

conf/local.conf.sample

Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>

accton-as4630-54pe: add platform to local.conf.sample

---

release-notes.txt

Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

release-notes.txt: added release notes for v4.4.0

---

default.xml
extra/tibit.xml

Update default.xml and extra/tibit.xml to the release v4.4.1 defaults.

default.xml extra/tibit.xml: update to v4.4.1 defaults

---

release-notes.txt

Update release notes with v4.4.1 ones.

release-notes.txt: update to v4.4.1

---

default.xml
extra/ofdpa-gitlab.xml
extra/tibit.xml

Add the appropriate release default.xml, so we can build release images.
Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

Add default.xml for release v4.5.0

---

release-notes.txt

Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

release-notes: added release notes for v4.5.0

---

release-notes.txt

Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>

release-notes: added release notes for v4.6.0

---

v4.6.1-releasenotes.txt

Initial attempt at writing the releasenotes for the v4.6.1 release
Comments and suggestions appreciated

releasenotes v4.6.1

---

README.md

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

add NOTE about failed builds related to CVE-2022-24765

---

default.xml
extra/ofdpa-gitlab.xml

Update default.xml and extra/ofdpa-gitlab.xml with release branch
revisions.

default.xml: set release branch revisions

---

default.xml

Make sure upgrade from earlier releases work.

default.xml: fix update from older releases

---

README.md

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

docs: update build instructions on how to use the docker-yocto-builder

---

README.md

Signed-off-by: Jan Klare <jan.klare@bisdn.de>

docs: explain how to set BRANCHNAME when bootstrapping build environment

---

default.xml

master is now main, so update the revisions to use it.

layers: switch revision from master to main

---

default.xml

Rename the meta-switch project to meta-bisdn-linux and reorder to keep the sub list alphabetical.

default.xml: update meta-switch => meta-bisdn-linux

---

BUILDING_DETAILS.md
README.md
rm-work.yaml

Document some build issues and possible solutions. Add a kas configuration file to reduce disk space use.

Expand documentation

---

.github/workflows/build-bisdn-linux.yml

Here's a run with a warm cache: https://github.com/ideaship/bisdn-linux/actions/runs/11685113686

Add github workflow for building BISDN Linux

---

README.md

Add a status badge for the CI pipeline to the README.md file and have the badge link to the CI pipeline.

workflow: add status badge to README.md
